
include /ioc/tools/driver.makefile

BUILDCLASSES=Linux
EXCLUDE_VERSIONS=3.13 3.14.8
#EXCLUDE_ARCHS=T2 V67 ppc603 ppc405 embeddedlinux-xscale_be 
EXCLUDE_ARCHS=T2 V67 ppc603 ppc405 embeddedlinux-xscale_be eldk42 eldk52


SOURCES+=./evrApp/src/asub.c
SOURCES+=./evrApp/src/devWfMailbox.c
#SOURCES+=./evrMrmApp/src/evrdump.c
SOURCES+=./evgMrmApp/src/seqnsls2.c
SOURCES+=./evgMrmApp/src/seqconst.c
#SOURCES+=./mrfCommon/src/linkoptionsTest.c
SOURCES+=./mrfCommon/src/devMbboDirectSoft.c
#SOURCES+=./mrfCommon/src/FracSynthAnalyze.c
SOURCES+=./mrfCommon/src/aSubRecord.c
SOURCES+=./mrfCommon/src/linkoptions.c
#SOURCES+=./mrfCommon/src/FracSynthControlWord.c
SOURCES+=./mrfCommon/src/mrfFracSynth.c


SOURCES+=./mrmShared/src/sfp.cpp
SOURCES+=./mrmShared/src/mrmDataBufTx.cpp
SOURCES+=./mrmShared/src/devMrfBufTx.cpp
SOURCES+=./evrApp/src/devEvrStringIO.cpp
SOURCES+=./evrApp/src/devEvrPulserMapping.cpp
SOURCES+=./evrApp/src/ntpShm.cpp
SOURCES+=./evrApp/src/devEvrEvent.cpp
SOURCES+=./evrApp/src/evrGTIF.cpp
SOURCES+=./evrApp/src/evr.cpp
#SOURCES+=./evrApp/src/ntpShmNull.cpp
#SOURCES+=./evrApp/src/evrMain.cpp
SOURCES+=./evrApp/src/devEvrMapping.cpp
SOURCES+=./evrMrmApp/src/drvemPulser.cpp
SOURCES+=./evrMrmApp/src/drvemIocsh.cpp
SOURCES+=./evrMrmApp/src/bufrxmgr.cpp
SOURCES+=./evrMrmApp/src/devMrmBufRx.cpp
SOURCES+=./evrMrmApp/src/drvem.cpp
SOURCES+=./evrMrmApp/src/drvemInput.cpp
SOURCES+=./evrMrmApp/src/drvemRxBuf.cpp
SOURCES+=./evrMrmApp/src/os/default/irqHack.cpp
#SOURCES+=./evrMrmApp/src/os/RTEMS/irqHack.cpp
#SOURCES+=./evrMrmApp/src/evrmrmMain.cpp
SOURCES+=./evrMrmApp/src/drvemPrescaler.cpp
SOURCES+=./evrMrmApp/src/drvemCML.cpp
SOURCES+=./evrMrmApp/src/drvemOutput.cpp
SOURCES+=./evgMrmApp/src/evgSequencer/evgSeqRam.cpp
SOURCES+=./evgMrmApp/src/evgSequencer/evgSoftSeq.cpp
SOURCES+=./evgMrmApp/src/evgSequencer/evgSeqRamManager.cpp
SOURCES+=./evgMrmApp/src/evgSequencer/evgSoftSeqManager.cpp
SOURCES+=./evgMrmApp/src/evgOutput.cpp
SOURCES+=./evgMrmApp/src/evgEvtClk.cpp
#SOURCES+=./evgMrmApp/src/evgMrmMain.cpp
SOURCES+=./evgMrmApp/src/evgSoftEvt.cpp
SOURCES+=./evgMrmApp/src/evgTrigEvt.cpp
SOURCES+=./evgMrmApp/src/devSupport/devEvgDbus.cpp
SOURCES+=./evgMrmApp/src/devSupport/devEvgTrigEvt.cpp
SOURCES+=./evgMrmApp/src/devSupport/devEvgMrm.cpp
SOURCES+=./evgMrmApp/src/devSupport/devEvgSoftSeq.cpp
SOURCES+=./evgMrmApp/src/evgAcTrig.cpp
SOURCES+=./evgMrmApp/src/evgDbus.cpp
SOURCES+=./evgMrmApp/src/evgMxc.cpp
SOURCES+=./evgMrmApp/src/evgInput.cpp
SOURCES+=./evgMrmApp/src/evgMrm.cpp
SOURCES+=./evgMrmApp/src/evg.cpp
SOURCES+=./evgMrmApp/src/evgInit.cpp
SOURCES+=./mrfCommon/src/mrfCommon.cpp
SOURCES+=./mrfCommon/src/devObjMBBDirect.cpp
SOURCES+=./mrfCommon/src/devObjWf.cpp
SOURCES+=./mrfCommon/src/devObjLong.cpp
SOURCES+=./mrfCommon/src/object.cpp
SOURCES+=./mrfCommon/src/devObjAnalog.cpp
SOURCES+=./mrfCommon/src/devObjString.cpp
SOURCES+=./mrfCommon/src/databuf.cpp
SOURCES+=./mrfCommon/src/devObjBinary.cpp
SOURCES+=./mrfCommon/src/objectTest.cpp
SOURCES+=./mrfCommon/src/devObjMBB.cpp
#SOURCES+=./mrmtestApp/src/mrfMain.cpp


DBDS+=./mrmShared/src/mrmShared.dbd
DBDS+=./evrApp/src/evrSupport.dbd
DBDS+=./evrMrmApp/src/drvemSupport.dbd
DBDS+=./evgMrmApp/src/evgInit.dbd
DBDS+=./mrfCommon/src/aSubRecord.dbd
DBDS+=./mrfCommon/src/mrfCommon.dbd
