###############################################################################
# Makefile -- Create the IOC Database File
###############################################################################

TOP=../..
include $(TOP)/configure/CONFIG

#=======================================
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#======================================

DB += evgMrmIOC.db


#===========================
#  ADD RULES AFTER THIS LINE
#===========================

include $(TOP)/configure/RULES
