TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

DB += evrbase.db
DB += evrmap.db
DB += evrout.db
DB += evrin.db
DB += evrscale.db
DB += evrpulser.db
DB += evrpulsermap.db
DB += evrcml.db
DB += evrcmlgun.db
DB += evrcmlextra.db
DB += evrevent.db
ifdef BASE_7_0
DB += evreventutag.db
endif
DB += evrevent-cycle.db
DB += evrsoftgate.db
DB += evralias.db
DB += evrNtp.db

DB += nsls2-egunfine.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
