name: Check EditorConfig

on:
  push: {}
  pull_request: {}

permissions:
  contents: read

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: EditorConfig compliance check
        uses: editorconfig-checker/action-editorconfig-checker@v2
